// Brush setting identity. Tags 0..64 are the table slots.
datatype SettingId =
  | SetOpaque
  | SetOpaqueMultiply
  | SetOpaqueLinearize
  | SetRadiusLogarithmic
  | SetHardness
  | SetSoftness
  | SetAntiAliasing
  | SetDabsPerBasicRadius
  | SetDabsPerActualRadius
  | SetDabsPerSecond
  | SetGridmapScale
  | SetGridmapScaleX
  | SetGridmapScaleY
  | SetRadiusByRandom
  | SetSpeed1Slowness
  | SetSpeed2Slowness
  | SetSpeed1Gamma
  | SetSpeed2Gamma
  | SetOffsetByRandom
  | SetOffsetY
  | SetOffsetX
  | SetN21
  | SetN22
  | SetN23
  | SetN24
  | SetN25
  | SetN26
  | SetN27
  | SetN28
  | SetN29
  | SetN30
  | SetSlowTracking
  | SetSlowTrackingPerDab
  | SetTrackingNoise
  | SetColorH
  | SetColorS
  | SetColorV
  | SetN37
  | SetChangeColorH
  | SetChangeColorL
  | SetN40
  | SetChangeColorV
  | SetN42
  | SetN43
  | SetPaintMode
  | SetN45
  | SetN46
  | SetN47
  | SetN48
  | SetN49
  | SetEraser
  | SetStrokeThreshold
  | SetStrokeDurationLog
  | SetStrokeHoldtime
  | SetN54
  | SetN55
  | SetEllipticalDabRatio
  | SetEllipticalDabAngle
  | SetDirectionFilter
  | SetLockAlpha
  | SetColorize
  | SetPosterize
  | SetPosterizeNum
  | SetSnapToPixel
  | SetPressureGainLog
  | SetNone

fun setting_of(i: int): SettingId = "ext#"
fun setting_ix(id: SettingId): int = "ext#"

