// src/draw_engine/settings.dats
#define ATS_DYNLOADFLAG 0
#include "share/atspre_define.hats"
#include "share/atspre_staload.hats"

// Sayısal Sabitler
#define BRUSH_INPUTS_COUNT 18
#define BRUSH_SETTINGS_COUNT 65
#define BRUSH_STATES_COUNT 44

// Fırça Ayarları (Settings)
#define BRUSH_SETTING_OPAQUE 0
#define BRUSH_SETTING_OPAQUE_MULTIPLY 1
#define BRUSH_SETTING_OPAQUE_LINEARIZE 2
#define BRUSH_SETTING_RADIUS_LOGARITHMIC 3
#define BRUSH_SETTING_HARDNESS 4
#define BRUSH_SETTING_SOFTNESS 5
#define BRUSH_SETTING_ANTI_ALIASING 6
#define BRUSH_SETTING_DABS_PER_BASIC_RADIUS 7
#define BRUSH_SETTING_DABS_PER_ACTUAL_RADIUS 8
#define BRUSH_SETTING_DABS_PER_SECOND 9
#define BRUSH_SETTING_GRIDMAP_SCALE 10
#define BRUSH_SETTING_GRIDMAP_SCALE_X 11
#define BRUSH_SETTING_GRIDMAP_SCALE_Y 12
#define BRUSH_SETTING_RADIUS_BY_RANDOM 13
#define BRUSH_SETTING_SPEED1_SLOWNESS 14
#define BRUSH_SETTING_SPEED2_SLOWNESS 15
#define BRUSH_SETTING_SPEED1_GAMMA 16
#define BRUSH_SETTING_SPEED2_GAMMA 17
#define BRUSH_SETTING_OFFSET_BY_RANDOM 18
#define BRUSH_SETTING_OFFSET_Y 19
#define BRUSH_SETTING_OFFSET_X 20
#define BRUSH_SETTING_SLOW_TRACKING 31
#define BRUSH_SETTING_SLOW_TRACKING_PER_DAB 32
#define BRUSH_SETTING_TRACKING_NOISE 33
#define BRUSH_SETTING_COLOR_H 34
#define BRUSH_SETTING_COLOR_S 35
#define BRUSH_SETTING_COLOR_V 36
#define BRUSH_SETTING_CHANGE_COLOR_H 38
#define BRUSH_SETTING_CHANGE_COLOR_L 39
#define BRUSH_SETTING_CHANGE_COLOR_V 41
#define BRUSH_SETTING_ERASER 50
#define BRUSH_SETTING_STROKE_THRESHOLD 51
#define BRUSH_SETTING_STROKE_DURATION_LOGARITHMIC 52
#define BRUSH_SETTING_STROKE_HOLDTIME 53
#define BRUSH_SETTING_ELLIPTICAL_DAB_RATIO 56
#define BRUSH_SETTING_ELLIPTICAL_DAB_ANGLE 57
#define BRUSH_SETTING_DIRECTION_FILTER 58
#define BRUSH_SETTING_LOCK_ALPHA 59
#define BRUSH_SETTING_COLORIZE 60
#define BRUSH_SETTING_POSTERIZE 61
#define BRUSH_SETTING_POSTERIZE_NUM 62
#define BRUSH_SETTING_SNAP_TO_PIXEL 63
#define BRUSH_SETTING_PRESSURE_GAIN_LOG 64
#define BRUSH_SETTING_PAINT_MODE 44

// Fırça Durumları (States)
#define BRUSH_STATE_X 0
#define BRUSH_STATE_Y 1
#define BRUSH_STATE_PRESSURE 2
#define BRUSH_STATE_PARTIAL_DABS 3
#define BRUSH_STATE_ACTUAL_RADIUS 4
#define BRUSH_STATE_ACTUAL_X 14
#define BRUSH_STATE_ACTUAL_Y 15
#define BRUSH_STATE_NORM_DX_SLOW 16
#define BRUSH_STATE_NORM_DY_SLOW 17
#define BRUSH_STATE_NORM_SPEED1_SLOW 18
#define BRUSH_STATE_NORM_SPEED2_SLOW 19
#define BRUSH_STATE_STROKE 20
#define BRUSH_STATE_STROKE_STARTED 21
#define BRUSH_STATE_ACTUAL_ELLIPTICAL_DAB_RATIO 24
#define BRUSH_STATE_ACTUAL_ELLIPTICAL_DAB_ANGLE 25
#define BRUSH_STATE_VIEWZOOM 30
#define BRUSH_STATE_VIEWROTATION 31
#define BRUSH_STATE_FLIP 35
#define BRUSH_STATE_DABS_PER_BASIC_RADIUS 40
#define BRUSH_STATE_DABS_PER_ACTUAL_RADIUS 41
#define BRUSH_STATE_DABS_PER_SECOND 42

